### ISSUE TITLE
Error when when trying to go to "quick sign in" 

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack-app-generator#10]
At this point in the _Hello Blockstack_ tutorial, the developer has not installed Blockstack and is supposed to be navigated to the quick sign in page after clicking "Sign In with Blockstack"

An error pops up..

![screen shot 2017-05-20 at 4 06 54 pm](https://cloud.githubusercontent.com/assets/5605552/26279028/ef186014-3d76-11e7-92f3-ea3c0e89e3e3.png)
![screen shot 2017-05-20 at 4 06 06 pm](https://cloud.githubusercontent.com/assets/5605552/26279029/f0b8c1de-3d76-11e7-895d-d85eabaa483e.png)

**Comment by pstan26** [comment]
cc @larrysalibra @shea256 

This is important because otherwise it will be nearly impossible for a user to complete the tutorial.

**Comment by larrysalibra** [comment]
@pstan26 This is because on safari (and edge AFAIK), there's no way for us to detect whether or not the user has installed blockstack by checking for the `blockstack:` protocol.

On these browsers, we could check to see if the user has a blockstack core node configured on the default port (by attempting to get http://localhost:6270/v1/node/ping), if they do, we could try `blockstack:` and if not, we could send to the "quick login` page. cc @shea256

**Comment by jackzampolin** [comment]
Stale, closing
